---
title: "Academic and Professional Experience"
---

## **Education**

Columbia University, **Master in Biostatistics Candidate             			          May 2022**

Winston-Salem State University, **Bachelor of Science in Mathematics                May 2020**

*   Major: Mathematics GPA: 3.6
* 	Concentration: Statistics


## **Key Skills**

Proficient in SAS/STAT, SAS/Base, R, Java, Microsoft Word, Excel and PowerPoint


## **Relevant Coursework**

Successful completion of relevant coursework in:

*   Abstract Algebra
*   Differential Equations
*   Real Analysis Statistics
*   Biostatistics
*   Business & Economics Statistics
*   Linear Algebra
*   Calculus I, II, III, and IV
*   Geometry
*   Foundations of Modern Mathematics
*   Methods of Regression/Analysis of Variance
*   Mathematical Statistics

## **Professional Experience**

**Intern**                                                                                                                05/2019 - 07/2019                        
Biostatistics and Epidemiology Summer Training Program, Columbia University, Mailman School of Public Health, New York, NY                                                  

*   Extracted, manipulated, and analyzed data

*   Examine the effects of  moderate-to-vigorous intensity physical activity eliminate the detrimental association of sedentary behavior with mortality

*   Gained exposure and reinforcement in SAS and the field of biostatistics and epidemiology 

**Research Assistant**                                                                                                    07/2018 - 05/2020

Department of Mathematics, Winston-Salem State University, Winston-Salem, NC                               

*	Extract, manipulate, and analyze public use data from the Action for Health in Diabetes (Look AHEAD) clinical trial. 
*	Conduct a series of secondary data analyses to identify an optimal marker of biological aging among people who are obese and have type-2 diabetes population.

**Professional Peer Tutor**                                                                                               08/2018 - 05/2020

Winston-Salem State University, Winston-Salem, NC   

*   Provide instructors assistance and assistant students with reviewing all materials for successful completion of undergraduate mathematics and statistics courses
*   Competency in algebra, geometry, statistics, calculus, and trigonometry


**Intern**                                                                                                                09/2017 - 05/2018

Financial Engineering and Applied Mathematics, Baruch College, New York, NY                                                                                                           

*   Explored mathematical finance in an enhanced curriculum highlighting the essential theory that forms the basis for academically studying investments and the stock market

*   Draws from areas of computer science, numerical methods, economics, calculus, linear algebra, and differential equations

*   Exploration and investigation of the various applied mathematics topics necessary to understand basic research literature describing financial engineering models used in practice.


## **Participation in National Scientific Meetings, Technical Conferences, Workshops, Seminar, Etc**

*   Participant, Joint Statistical Meeting (JSM) Diversity Workshop &  Mentoring Program, Denver Colorado, Summer 2019
    
*   Poster presentation, Examine the effects of  moderate-to-vigorous intensity physical activity eliminate the detrimental association of sedentary behavior with mortality, Biostatistics and Epidemiology Summer Training Program, Columbia University, New York, NY, Summer, 2019

*   Poster presentation, An Examination of on Frailty Through the Lens of Deficit Accumulation in Adults with Type 2 Diabetes Mellitus, Scholarship Day, Winston-Salem State University, Winston-Salem, NC, Spring, 2019   

*   Participant, Eastern North American Region of the International Biometric Society (ENAR) Fostering Diversity in Biostatistics Workshop, Philadelphia, Pennsylvania, Spring 2019 

*   Participant, Mathematics Workforce Development Conference, Winston-Salem State and North Carolina A&T, Winston-Salem, NC, Fall, 2017   

*   Participant, Statfest 2017 Conference, Emory University, Atlanta, Ga, Fall 2017


## **Professional Memberships**

*   Member, American Statistical Association                                                                      2019 – present
*   Member, Mathematical Association of America                                                                   2019 – present
*   President, Mathematics and Statistics Club, Winston-Salem State University                                    2017 – present

## **Volunteering Experience**

**Elementary Mathematics Invitational**   					                                                                             04/26/2019 

Winston-Salem State University, Winston-Salem, NC

*   Assist with the registration, set up and successful execution of mathematics activities for elementary students  

**Beyond the Classroom**                                                                                                         03/04/2019

Forest Park Elementary School, Winston-Salem, NC

*   Incorporate statistical reinforcement with physical activities to grade pre-k to 5th

## **Bibliography**

*   Simpson FR, Espeland MA, **Ojeranti D**, Ingram F, Bertoni A, Nicklas B Impact of Multidomain Lifestyle Intervention on Frailty Through the Lens of Deficit Accumulation in Adults with Type 2 Diabetes Mellitus,. Journal of Gerontology: Medical Sciences. Submitted.

* 	Felicia R Simpson, PhD, Nicholas M Pajewski, PhD, Kristen M Beavers, PhD, Stephen Kritchevsky, PhD, Jeanne McCaffery, PhD, Barbara J Nicklas, PhD, Rena R Wing, PhD, Alain Bertoni, MD, Frank Ingram, PhD, **Daniel Ojeranti**, Mark A Espeland, PhD. (2020) Indices for Accelerated Aging in Obesity and Diabetes Ancillary Study of the Action for Health in Diabetes (Look AHEAD) Trial, Does the impact of intensive lifestyle intervention on cardiovascular disease vary according to frailty measured via deficit accumulation?, The Journals of Gerontology: Series A, 10.1093/gerona/glaa153




[About me](about.html)