---
title: "Instacart Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r, warning = FALSE, message = F}
library(tidyverse)
library(p8105.datasets)
library(hexbin)
library(ggridges)
library(patchwork)
library(plotly)
library(flexdashboard)
knitr::opts_chunk$set(
	fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

```{r}
data("instacart")
instacart.third =
 instacart %>% 
  slice_sample(n = 500000  )
```


### Scatterplot

```{r}

instacart.third %>% 
	count(aisle) %>% 
	filter(n > 10000) %>% 
	mutate(
		aisle = factor(aisle),
		aisle = fct_reorder(aisle, n)
	) %>% 
  plot_ly(
    x = ~aisle, y = ~n, type = "scatter", mode = "markers",
    color = ~aisle, text = ~aisle, alpha = 0.5)
```


### Boxplot

```{r}

instacart.third %>% 
	filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
	group_by(aisle) %>% 
	count(product_name) %>% 
  plot_ly(x = ~aisle, y = ~product_name, color = ~aisle, type = "box", colors = "viridis")
```

### Bargraph

```{r}
instacart.third %>% 
  count(aisle) %>% 
	filter(n > 10000) %>% 
	mutate(
		aisle = factor(aisle),
		aisle = fct_reorder(aisle, n)
	) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis")
```